### ISSUE TITLE
Double precision should be configurable in exported data

### ISSUE THREAD

**Issue by cric96** [AlchemistSimulator/Alchemist#1164]
Currently, when we export double data from Alchemist simulations, it does not allow us to configure the precision of the number that will be exported. In this way, the generated CSV, contains unuseful information, producing unnecessary large files.

**Comment by DanySK** [comment]
I'm looking into this. We could use [`DecimalFormat`](https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html), but we have the problem of customizing infinity and nan values, plus it will be either always exponential or never exponential.

**Comment by DanySK** [comment]
The `%g` looks like a better fit for this simple problem

**Comment by cric96** [comment]
> The `%g` looks like a better fit for this simple problem

I think it is a good choice! I would use the precision parameter anyway, and use `%g` like this:
```
"%.${precision}g".format(value)
```
