### ISSUE TITLE
Add OutputMonitor to the simulation through YAML configuration

### ISSUE THREAD

**Issue by w4bo** [AlchemistSimulator/Alchemist#22]
I think it could be useful to give the simulation designer the chance to add custom `OutputMonitor` to the simulation without the need to modify the `AlchemistRunner` class. The Alchemist YAML configuration could be a good place to specify which custom observers have to be added to the simulation.

**Comment by DanySK** [comment]
This is useful, I agree

**Comment by DanySK** [comment]
Terminators partially address this need, directly from the YAML

**Comment by DanySK** [comment]
Support for custom OutputMonitors has been added to AlchemistRunner. Further work will be deferred until a use case comes out.
