### ISSUE TITLE
Unable to select custom launcher with the new CLI

### ISSUE THREAD

**Issue by kelvin-olaiya** [AlchemistSimulator/Alchemist#2554]
I was trying to run Alchemist in server mode with the following configuration file:

```yml
incarnation: protelis
launcher:
  type: AlchemistServer
```

(here `AlchemistServer` refers to `IgniteServerLauncher`).

The problem is that it launches with the `HeadlessSimulationLauncher` which I understand is the default.

Here's the output

```txt
14:52:34.299 [alchemist-executor-0] WARN it.unibo.alchemist.boundary.loader.SimulationModel -- No seeds specified, defaulting to 0 for both scenario and simulation
LOGBACK: No context given for ch.qos.logback.core.ConsoleAppender[null]
14:52:34.322 [alchemist-executor-0] WARN it.unibo.alchemist.boundary.loader.SimulationModel -- No environment specified, defaulting to Continuous2DEnvironment
14:52:34.341 [alchemist-executor-0] WARN it.unibo.alchemist.boundary.loader.SimulationModel -- There are no displacements in the specification, the environment won't have any node
```

**Comment by DanySK** [comment]
Can you run it in verbose mode?

**Comment by DanySK** [comment]
Definitely a bug. Can you please open a PR with a test that "fails correctly"?
Thanks

**Comment by DanySK** [comment]
@kelvin-olaiya the test looks partially broken: 

```
        java.lang.IllegalArgumentException: Illegal Alchemist specification: Could not create IgniteServerLauncher(), requested as instance of IgniteServerLauncher.
        Actual parameters: []
          - constructor: IgniteServerLauncher(String)
            failure message 1 of InstancingImpossibleException: Could not create an instance with public i.u.a.boundary.launchers.IgniteServerLauncher(String): discarded because incompatible with provided parameters []
```

You are missing a string parameter. Still, the system should fail and not fallback to headless silently

**Comment by DanySK** [comment]
Only if the constructor is annotated with `@JvmOverloads` and the default is `null`. If desirable, leave the test as is and update the constructor instead

**Comment by kelvin-olaiya** [comment]
Since very likely I'll move away from Ignite, I'll add the config file to fix test. I'll consider this aspect for the new implementation.
Thanks
