### ISSUE TITLE
Silent failure when loading OSM traces

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#27]
While useful for interesting creativity exercises and for training guesses, it might be useful to notify when traces are not loaded by `OSMEnvironment`.

**Comment by DanySK** [comment]
@gscaparrotti, since you are currently working on this part, formulate a refactoring proposal for the constructors of OSMEnvironment.

**Comment by gscaparrotti** [comment]
I'll work on it.

**Comment by DanySK** [comment]
This won't be ready for Alchemist 6. Moving to Alchemist 7.

**Comment by DanySK** [comment]
The new GPS trace system has been merged to develop.
