### ISSUE TITLE
Modification of the details of an effect while the simulation is running

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#29]
Trying to change e.g. field "Molecule property" in an effect while the simulation is running causes the production of hundreds of exception messages, such as the following one (I was trying to digit "true"), in the console:

```
java.lang.IllegalArgumentException: The Protelis program cannot be created because of the following errors:
Error, line 1: Couldn't resolve reference to EObject 't'.
Error, line 1: Couldn't resolve reference to EObject 'tr'
```

It might be better to log it at debug-level, and/or to defer the parsing until the change is committed.

**Comment by DanySK** [comment]
Closing as won't fix. Unfortunately, those prints are more useful than not when debugging broken effects.
