### ISSUE TITLE
The Incarnation should not support nullable nodes

### ISSUE THREAD

**Issue by angelacorte** [AlchemistSimulator/Alchemist#3070]
In the [Incarnation](https://github.com/AlchemistSimulator/Alchemist/blob/master/alchemist-api/src/main/java/it/unibo/alchemist/model/Incarnation.java) interface there are many methods like `createTimeDistribution`, `createCondition` and `createAction` that accept a nullable node.
I think that this is wrong, because in simulations we don't want that nodes can become null.

**Comment by DanySK** [comment]
I looked at this. Nullable nodes serve for Global Reactions. Won't fix.
