### ISSUE TITLE
Invalid scm url

### ISSUE THREAD

**Issue by IgnatBeresnev** [AlchemistSimulator/Alchemist#3506]
Services like https://klibs.io might rely on scm urls to group artifacts under the same project

It seems like this repository publishes a couple of Kotlin Multiplatform artifacts that have the wrong scm url set (although I'm not sure if it's this repo or some other).

Could you please check and correct it, if possible?

```
+------------------+----------------------+------------------------------------------------+--------------------------+-------+
|group_id          |artifact_id           |scm_url                                         |release_ts                |version|
+------------------+----------------------+------------------------------------------------+--------------------------+-------+
|it.unibo.alchemist|alchemist-web-renderer|https://github.com/DanySK/alchemist-web-renderer|2024-06-05 06:22:26.000000|34.0.8 |
|it.unibo.alchemist|alchemist-graphql     |https://github.com/DanySK/alchemist-graphql     |2024-06-05 06:22:22.000000|34.0.8 |
|it.unibo.alchemist|alchemist-full        |https://github.com/DanySK/alchemist-full        |2024-06-05 06:22:21.000000|34.0.8 |
+------------------+----------------------+------------------------------------------------+--------------------------+-------+
```

**Comment by DanySK** [comment]
Thanks for bringing this up. From a quick look, it seems like an issue with https://github.com/DanySK/publish-on-central, which also affects other multiplatform repos: https://search.maven.org/artifact/org.danilopianini/template-for-kotlin-multiplatform-projects-js/0.1.26/klib

It is a strange issue, I'll investigate.

**Comment by DanySK** [comment]
Ouch. It is much simpler, it looks like I forgot to configure the projectUrl in the publish-on-central plugin. All projects are broken, not just the multiplatform ones.

**Comment by DanySK** [comment]
Unless I wrote broken stuff, #3509 will automatically rebase onto master and cause  a new, fixed release by tomorrow morning CET. Thanks for opening the report.
