### ISSUE TITLE
IllegalStateException when using molecule without concentration with Protelis Incarnation

### ISSUE THREAD

**Issue by Piero93** [AlchemistSimulator/Alchemist#38]
Chosing Protelis incarnation, when using a molecule and concentration line is missing or has an empty value or a null value the program crashes throwing an IllegalStateException.

**Comment by DanySK** [comment]
This only affects Protelis, and it is actually a bug in Protelis.

**Comment by DanySK** [comment]
Closing, as the proper report is now [open on the Protelis GitHub](https://github.com/Protelis/Protelis/issues/135).
