### ISSUE TITLE
CI workflow always fails in forked repository

### ISSUE THREAD

**Issue by aPlacuzzi** [AlchemistSimulator/Alchemist#720]
The `Deploy` step always tries to deploy artifacts when `build` and `check` steps successfully complete. 
Forked repositories haven't the credentials to deploy to remote repositories (and they shouldn't deploy).

The result is that the CI always fails in a forked repository also if the project status is correct.

**Comment by DanySK** [comment]
Pull develop and retry, see if the patch works as expected.

**Comment by aPlacuzzi** [comment]
It works
