### ISSUE TITLE
Shape rectangle doesn't accept negative height and width

### ISSUE THREAD

**Issue by aPlacuzzi** [AlchemistSimulator/Alchemist#82]
when inserting negative values of height or width the rectangle isn't drawn and no exception is throwed

**Comment by DanySK** [comment]
@Placu95 is this fixed? Can you add a regression test if it's not there already?

**Comment by Placu95** [comment]
I check it now with the last version of Alchemist.
the bug is still present.

**Comment by DanySK** [comment]
Since you checked, can you add a test (that will fail)?

**Comment by Placu95** [comment]
Sure, I try to add it

**Comment by Placu95** [comment]
open PR with the required test

**Comment by DanySK** [comment]
Fixed. Thanks
