### ISSUE TITLE
Adjustments to scafi-alchemist-incarnation

### ISSUE THREAD

**Issue by metaphori** [AlchemistSimulator/Alchemist#93]
- `ScafiIncarnation.scala`: specify msg on `requireNonNull` call in `createTimeDistribution`
- See Scala-related deprecation warnings
- **Consider separating scafi program with `send` program (in Protelis)** which is used to decouple computation and neighbourhood communication (used e.g. to calculate network lags)
- Adjust `ScafiNode` by fixing `createT` by making it return null or raise `NullPointerException` if a certain molecule is not present in the node

**Comment by DanySK** [comment]
@metaphori what's the status on this?

**Comment by metaphori** [comment]
These should have been fixed by

- #116 
- #301 
- #711
